---
- name: modify centos packer template file
  lineinfile:
     regexp: '(\s+)"headless": ""'
     line: '\1"headless": "true",'
     backrefs: yes
     path: "{{ centos_packer_file }}"

- name: build centos box
  shell: "packer build -only qemu {{ centos_packer_file | basename }}"
  args:
    chdir:  "{{ centos_packer_file | dirname }}"
    creates: "{{ centos_packer_file | dirname }}/../builds/centos-{{centos_version}}.libvirt.box"
  register: packer_build

- block:
    - name: check if centos vagrant box is installed
      shell: vagrant box list | grep centos7
      changed_when: false
  rescue:
    - name: install centos vagrant box
      shell: " vagrant box add  {{ centos_packer_file | dirname }}/../builds/centos-{{centos_version}}.libvirt.box --name centos7"
